export const NANOID_LENGTH_DEFAULT = 21;
export const USER_ID_LENGTH = 15;
export const PROJECT_ID_LENGTH = NANOID_LENGTH_DEFAULT;
export const ORGANIZATION_ID_LENGTH = NANOID_LENGTH_DEFAULT;
export const USER_PROJECTS_COLLECTION_ID_LENGTH = NANOID_LENGTH_DEFAULT;
