packages:
  # SvelteKit app
  - 'frontend/**'
  # SvelteKit app v2 (svelte 4)
  - 'frontend2/**'
  # Utility packages
  - 'icons/**'
  - 'theme/**'
  # Mixed general purpose contents for github, docs, or public references
  - 'misc/**'
  # Markdown-based documentation
  - 'documentation/**'
