packages:
  # SvelteKit app
  - 'frontend/**'
  # SvelteKit app v2 (svelte 4)
  - 'frontend-2/**'
  # Supabase db and functions
  - 'database/**'
  # Mixed general purpose contents for github, docs, or public references
  - 'misc/**'
  # Markdown-based documentation
  - 'documentation/**'
