import { colord } from 'colord';
import { writeFile } from 'fs';
import { resolve } from 'path';
import prettier from 'prettier';
import type { Plugin } from 'vite';
import { flatten } from '../../lib/utils/object';
import { PRETTIER_CONFIG } from '../common';
import type { Theme } from './utils';

const OUTPUT_STYLES = resolve('src', 'lib', 'styles', 'themes.css');
const COMMENT = `/*\n* ⚠️ WARNING ⚠️\n*\n* This file was generated by the styles vite-plugin. All changes added manually here will be lost on next iteration run of plugin's generators.\n*\n* Generated at: ${new Date()}\n*\n* ⚠️ WARNING ⚠️\n*/`;

/**
 * Generate fadeable rgb components for a color.
 */
function fade(color: string) {
	const { r, g, b } = colord(color).toRgb();
	return `${r}, ${g}, ${b}`;
}

/**
 * Compose css custom properties.
 */
function vars(
	object: object,
	format: (k: string, v: string | number) => [k: string, v: string | number]
) {
	return flatten(object)
		.map(([keys, val]) => {
			const [k, v] = format(keys.join('-'), val);
			return `--${k}: ${v}`;
		})
		.join('; ');
}

/**
 * Preprocess a given record of themes and output the corresponding css variables declaration into a
 * global style file.
 */
export default function plugin(themes: Record<string, Theme>): Plugin {
	function writeStyles() {
		try {
			const statements = [
				COMMENT,
				...Object.entries(themes).map(([t, c]) => {
					return `[data-theme="${t}"] {
						${vars(c, (k, v) => ['color-' + k, v])};
						${vars(c, (k, v) => ['rgb-' + k, fade(v + '')])};
					}`;
				}),
			];

			const formatted = prettier.format(statements.join('\n\n'), {
				parser: 'css',
				...PRETTIER_CONFIG,
			});

			writeFile(OUTPUT_STYLES, formatted, (error) => {
				if (error) throw error;
				else console.info('Style themes globals generated successfully.');
			});
		} catch (error) {
			console.error('Error generating theme.', error);
		}
	}

	return {
		name: 'nplex-themes',
		config() {
			writeStyles();
		},
		buildStart() {
			writeStyles();
		},
	};
}
