create table "public"."project_exemplarity_indicator_category" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "title" text not null,
    "description" text
);


alter table "public"."project_exemplarity_indicator_category" enable row level security;

create table "public"."projects_programs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "created_by_id" uuid not null default auth.uid(),
    "updated_at" timestamp with time zone not null default now(),
    "updated_by_id" uuid not null default auth.uid(),
    "project_id" uuid not null,
    "title" text not null,
    "description" text not null
);


alter table "public"."project_exemplarity_indicator" add column "category_id" bigint;

alter table "public"."project_exemplarity_indicator" add column "created_at" timestamp with time zone not null default now();

alter table "public"."project_exemplarity_indicator" add column "updated_at" timestamp with time zone not null default now();

alter table "public"."projects" add column "combustible" boolean not null;

alter table "public"."projects_exemplarity_indicators" add column "rating" numeric not null;

CREATE UNIQUE INDEX project_exemplarity_indicator_category_pkey ON public.project_exemplarity_indicator_category USING btree (id);

CREATE UNIQUE INDEX projects_programs_pkey ON public.projects_programs USING btree (id);

alter table "public"."project_exemplarity_indicator_category" add constraint "project_exemplarity_indicator_category_pkey" PRIMARY KEY using index "project_exemplarity_indicator_category_pkey";

alter table "public"."projects_programs" add constraint "projects_programs_pkey" PRIMARY KEY using index "projects_programs_pkey";

alter table "public"."project_exemplarity_indicator" add constraint "project_exemplarity_indicator_category_id_fkey" FOREIGN KEY (category_id) REFERENCES project_exemplarity_indicator_category(id) not valid;

alter table "public"."project_exemplarity_indicator" validate constraint "project_exemplarity_indicator_category_id_fkey";

alter table "public"."projects_programs" add constraint "projects_programs_created_by_id_fkey" FOREIGN KEY (created_by_id) REFERENCES users_profiles(user_id) not valid;

alter table "public"."projects_programs" validate constraint "projects_programs_created_by_id_fkey";

alter table "public"."projects_programs" add constraint "projects_programs_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE not valid;

alter table "public"."projects_programs" validate constraint "projects_programs_project_id_fkey";

alter table "public"."projects_programs" add constraint "projects_programs_updated_by_id_fkey" FOREIGN KEY (updated_by_id) REFERENCES users_profiles(user_id) not valid;

alter table "public"."projects_programs" validate constraint "projects_programs_updated_by_id_fkey";


create policy "Enable read access for all users"
on "public"."project_exemplarity_indicator_category"
as permissive
for select
to public
using (true);



