create extension if not exists "moddatetime" with schema "public" version '1.0';

create schema if not exists "postgis";

grant usage on schema "postgis" to "postgres";

create extension if not exists "postgis" with schema "postgis";

create type "public"."publication_status" as enum ('unpublished', 'pending_approval', 'refused_approval', 'published');

create type "public"."user_role" as enum ('admin', 'editor', 'visitor');

create table "public"."project_category" (
    "id" smallint generated by default as identity not null,
    "title" text not null,
    "description" text
);


alter table "public"."project_category" enable row level security;

create table "public"."project_event_child_type" (
    "id" smallint generated by default as identity not null,
    "type_id" smallint not null,
    "child_type_id" smallint not null
);


alter table "public"."project_event_child_type" enable row level security;

create table "public"."project_event_type" (
    "id" smallint generated by default as identity not null,
    "title" text not null,
    "description" text,
    "durative" boolean not null
);


alter table "public"."project_event_type" enable row level security;

create table "public"."project_exemplarity_indicator" (
    "id" smallint generated by default as identity not null,
    "title" text not null,
    "description" text
);


alter table "public"."project_exemplarity_indicator" enable row level security;

create table "public"."project_implantation_mode" (
    "id" smallint generated by default as identity not null,
    "title" text not null,
    "description" text
);


alter table "public"."project_implantation_mode" enable row level security;

create table "public"."project_material_origin" (
    "id" smallint generated by default as identity not null,
    "title" text not null,
    "label" text not null,
    "description" text
);


alter table "public"."project_material_origin" enable row level security;

create table "public"."project_material_type" (
    "id" integer generated by default as identity not null,
    "title" text not null,
    "label" text,
    "description" text,
    "combustible" boolean
);


alter table "public"."project_material_type" enable row level security;

create table "public"."project_material_use" (
    "id" integer generated by default as identity not null,
    "title" text not null,
    "description" text
);


alter table "public"."project_material_use" enable row level security;

create table "public"."project_site_ownership" (
    "id" smallint generated by default as identity not null,
    "title" text not null,
    "description" text
);


alter table "public"."project_site_ownership" enable row level security;

create table "public"."project_site_usage" (
    "id" smallint generated by default as identity not null,
    "title" text not null,
    "description" text
);


alter table "public"."project_site_usage" enable row level security;

create table "public"."project_site_usage_category" (
    "id" smallint generated by default as identity not null,
    "title" text not null,
    "description" text
);


alter table "public"."project_site_usage_category" enable row level security;

create table "public"."project_site_usage_parent_category" (
    "id" smallint generated by default as identity not null,
    "usage_id" smallint not null,
    "category_id" smallint not null
);


alter table "public"."project_site_usage_parent_category" enable row level security;

create table "public"."project_type" (
    "id" smallint generated by default as identity not null,
    "title" text not null,
    "description" text
);


alter table "public"."project_type" enable row level security;

create table "public"."project_type_parent_category" (
    "category_id" smallint not null,
    "type_id" smallint not null
);


alter table "public"."project_type_parent_category" enable row level security;

create table "public"."projects" (
    "id" uuid not null default uuid_generate_v4(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "created_by_id" uuid not null default auth.uid(),
    "updated_by_id" uuid not null default auth.uid(),
    "title" text not null,
    "description" text,
    "site_ownership_id" smallint,
    "site_usage_category_id" smallint,
    "site_usage_id" smallint,
    "site_area" numeric,
    "category_id" smallint not null,
    "area" numeric,
    "adjacent_streets" smallint,
    "location_geometry" postgis.geometry not null,
    "building_area" numeric,
    "implantation_mode_id" smallint,
    "building_construction_year" smallint,
    "cost_min" integer not null,
    "cost_max" integer not null,
    "type_id" smallint not null
);


alter table "public"."projects" enable row level security;

create table "public"."projects_events" (
    "id" uuid not null default uuid_generate_v4(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "created_by_id" uuid not null default auth.uid(),
    "updated_by_id" uuid not null default auth.uid(),
    "project_id" uuid not null,
    "type_id" smallint not null,
    "parent_id" uuid,
    "title" text not null,
    "description" text,
    "start_date" timestamp with time zone not null,
    "end_date" timestamp with time zone
);


create table "public"."projects_events_ressources" (
    "id" uuid not null default uuid_generate_v4(),
    "event_id" uuid not null,
    "project_id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "created_by_id" uuid not null default auth.uid(),
    "updated_by_id" uuid not null default auth.uid(),
    "title" text not null,
    "description" text
);


create table "public"."projects_exemplarity_indicators" (
    "id" uuid not null default uuid_generate_v4(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "created_by_id" uuid not null default auth.uid(),
    "updated_by_id" uuid not null default auth.uid(),
    "project_id" uuid not null,
    "exemplarity_indicator_id" smallint not null,
    "description" text
);


create table "public"."projects_materials" (
    "id" uuid not null default uuid_generate_v4(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "created_by_id" uuid not null default auth.uid(),
    "updated_by_id" uuid not null default auth.uid(),
    "project_id" uuid not null,
    "material_type_id" integer not null,
    "origin_id" smallint,
    "sustainability" numeric(1,1),
    "description" text
);


create table "public"."projects_materials_uses" (
    "id" integer generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "created_by_id" uuid not null default auth.uid(),
    "updated_by_id" uuid not null default auth.uid(),
    "project_id" uuid not null,
    "project_material_id" uuid not null,
    "material_use_id" integer not null,
    "description" text
);


create table "public"."projects_publication_status" (
    "project_id" uuid not null,
    "updated_at" timestamp with time zone not null default now(),
    "updated_by_id" uuid not null,
    "status" publication_status not null default 'unpublished'::publication_status
);


alter table "public"."projects_publication_status" enable row level security;

create table "public"."projects_ratings" (
    "id" integer generated by default as identity not null,
    "user_id" uuid not null,
    "project_id" uuid not null,
    "rating" numeric(2,1),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


alter table "public"."projects_ratings" enable row level security;

create table "public"."projects_users" (
    "id" integer generated by default as identity not null,
    "project_id" uuid not null,
    "user_id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "granted_role" user_role not null default 'editor'::user_role,
    "modified_at" timestamp with time zone not null default now()
);


alter table "public"."projects_users" enable row level security;

create table "public"."users_profiles" (
    "user_id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "published_email" text,
    "avatar_url" text,
    "firstname" text,
    "middlename" text,
    "lastname" text,
    "about" text
);


alter table "public"."users_profiles" enable row level security;

create table "public"."users_projects_collections" (
    "id" uuid not null default uuid_generate_v4(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "user_id" uuid not null default auth.uid(),
    "is_published" boolean not null default true,
    "title" text not null,
    "description" text
);


alter table "public"."users_projects_collections" enable row level security;

create table "public"."users_projects_collections_items" (
    "id" integer generated by default as identity not null,
    "user_id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "collection_id" uuid not null,
    "project_id" uuid not null,
    "comment" text
);


alter table "public"."users_projects_collections_items" enable row level security;

create table "public"."users_roles" (
    "user_id" uuid not null,
    "updated_at" timestamp with time zone not null default now(),
    "role" user_role not null default 'visitor'::user_role
);


alter table "public"."users_roles" enable row level security;

CREATE UNIQUE INDEX project_event_child_type_pkey ON public.project_event_child_type USING btree (type_id, child_type_id);

CREATE UNIQUE INDEX project_event_type_pkey ON public.project_event_type USING btree (id);

CREATE UNIQUE INDEX project_exemplarity_indicator_pkey ON public.project_exemplarity_indicator USING btree (id);

CREATE UNIQUE INDEX project_implantation_mode_pkey ON public.project_implantation_mode USING btree (id);

CREATE UNIQUE INDEX project_implantation_mode_title_key ON public.project_implantation_mode USING btree (title);

CREATE UNIQUE INDEX project_material_origin_label_key ON public.project_material_origin USING btree (label);

CREATE UNIQUE INDEX project_material_origin_pkey ON public.project_material_origin USING btree (id);

CREATE UNIQUE INDEX project_material_origin_title_key ON public.project_material_origin USING btree (title);

CREATE UNIQUE INDEX project_material_type_label_key ON public.project_material_type USING btree (label);

CREATE UNIQUE INDEX project_material_type_pkey ON public.project_material_type USING btree (id);

CREATE UNIQUE INDEX project_material_type_title_key ON public.project_material_type USING btree (title);

CREATE UNIQUE INDEX project_material_use_pkey ON public.project_material_use USING btree (id);

CREATE UNIQUE INDEX project_material_use_title_key ON public.project_material_use USING btree (title);

CREATE UNIQUE INDEX project_site_ownership_pkey ON public.project_site_ownership USING btree (id);

CREATE UNIQUE INDEX project_site_usage_by_category_pkey ON public.project_site_usage_parent_category USING btree (usage_id, category_id);

CREATE UNIQUE INDEX project_site_usage_by_category_usage_id_category_id_key ON public.project_site_usage_parent_category USING btree (usage_id, category_id);

CREATE UNIQUE INDEX project_site_usage_category_pkey ON public.project_site_usage_category USING btree (id);

CREATE UNIQUE INDEX project_site_usage_parent_category_usage_id_category_id_key ON public.project_site_usage_parent_category USING btree (usage_id, category_id);

CREATE UNIQUE INDEX project_site_usage_pkey ON public.project_site_usage USING btree (id);

CREATE UNIQUE INDEX project_sub_type_parent_type_pkey ON public.project_type_parent_category USING btree (category_id, type_id);

CREATE UNIQUE INDEX project_sub_type_parent_type_type_id_sub_type_id_key ON public.project_type_parent_category USING btree (category_id, type_id);

CREATE UNIQUE INDEX project_sub_type_pkey ON public.project_type USING btree (id);

CREATE UNIQUE INDEX project_sub_type_title_key ON public.project_type USING btree (title);

CREATE UNIQUE INDEX project_type_pkey ON public.project_category USING btree (id);

CREATE UNIQUE INDEX project_types_sub_types_type_id_sub_type_id_key ON public.project_type_parent_category USING btree (category_id, type_id);

CREATE UNIQUE INDEX projects_editors_project_id_editor_id_key ON public.projects_users USING btree (project_id, user_id);

CREATE UNIQUE INDEX projects_events_pkey ON public.projects_events USING btree (id);

CREATE UNIQUE INDEX projects_events_ressources_pkey ON public.projects_events_ressources USING btree (id);

CREATE UNIQUE INDEX projects_exemplarity_indicato_exemplarity_indicator_id_proj_key ON public.projects_exemplarity_indicators USING btree (exemplarity_indicator_id, project_id);

CREATE UNIQUE INDEX projects_exemplarity_indicators_pkey ON public.projects_exemplarity_indicators USING btree (id);

CREATE UNIQUE INDEX projects_materials_pkey ON public.projects_materials USING btree (id);

CREATE UNIQUE INDEX projects_materials_uses_pkey ON public.projects_materials_uses USING btree (id);

CREATE UNIQUE INDEX projects_pkey ON public.projects USING btree (id);

CREATE UNIQUE INDEX projects_publication_status_pkey ON public.projects_publication_status USING btree (project_id);

CREATE UNIQUE INDEX projects_publication_status_project_id_key ON public.projects_publication_status USING btree (project_id);

CREATE UNIQUE INDEX projects_ratings_pkey ON public.projects_ratings USING btree (id, user_id, project_id);

CREATE UNIQUE INDEX projects_ratings_project_id_user_id_key ON public.projects_ratings USING btree (project_id, user_id);

CREATE UNIQUE INDEX projects_ratings_user_id_project_id_key ON public.projects_ratings USING btree (user_id, project_id);

CREATE UNIQUE INDEX projects_title_key ON public.projects USING btree (title);

CREATE UNIQUE INDEX projects_users_pkey ON public.projects_users USING btree (id, project_id, user_id);

CREATE UNIQUE INDEX projects_users_user_id_project_id_key ON public.projects_users USING btree (user_id, project_id);

CREATE UNIQUE INDEX users_profiles_pkey ON public.users_profiles USING btree (user_id);

CREATE UNIQUE INDEX users_profiles_user_id_key ON public.users_profiles USING btree (user_id);

CREATE UNIQUE INDEX users_projects_collections_items_collection_id_project_id_key ON public.users_projects_collections_items USING btree (collection_id, project_id);

CREATE UNIQUE INDEX users_projects_collections_items_pkey ON public.users_projects_collections_items USING btree (id);

CREATE UNIQUE INDEX users_projects_collections_pkey ON public.users_projects_collections USING btree (id);

CREATE UNIQUE INDEX users_roles_pkey ON public.users_roles USING btree (user_id);

CREATE UNIQUE INDEX users_roles_user_id_key ON public.users_roles USING btree (user_id);

alter table "public"."project_category" add constraint "project_type_pkey" PRIMARY KEY using index "project_type_pkey";

alter table "public"."project_event_child_type" add constraint "project_event_child_type_pkey" PRIMARY KEY using index "project_event_child_type_pkey";

alter table "public"."project_event_type" add constraint "project_event_type_pkey" PRIMARY KEY using index "project_event_type_pkey";

alter table "public"."project_exemplarity_indicator" add constraint "project_exemplarity_indicator_pkey" PRIMARY KEY using index "project_exemplarity_indicator_pkey";

alter table "public"."project_implantation_mode" add constraint "project_implantation_mode_pkey" PRIMARY KEY using index "project_implantation_mode_pkey";

alter table "public"."project_material_origin" add constraint "project_material_origin_pkey" PRIMARY KEY using index "project_material_origin_pkey";

alter table "public"."project_material_type" add constraint "project_material_type_pkey" PRIMARY KEY using index "project_material_type_pkey";

alter table "public"."project_material_use" add constraint "project_material_use_pkey" PRIMARY KEY using index "project_material_use_pkey";

alter table "public"."project_site_ownership" add constraint "project_site_ownership_pkey" PRIMARY KEY using index "project_site_ownership_pkey";

alter table "public"."project_site_usage" add constraint "project_site_usage_pkey" PRIMARY KEY using index "project_site_usage_pkey";

alter table "public"."project_site_usage_category" add constraint "project_site_usage_category_pkey" PRIMARY KEY using index "project_site_usage_category_pkey";

alter table "public"."project_site_usage_parent_category" add constraint "project_site_usage_by_category_pkey" PRIMARY KEY using index "project_site_usage_by_category_pkey";

alter table "public"."project_type" add constraint "project_sub_type_pkey" PRIMARY KEY using index "project_sub_type_pkey";

alter table "public"."project_type_parent_category" add constraint "project_sub_type_parent_type_pkey" PRIMARY KEY using index "project_sub_type_parent_type_pkey";

alter table "public"."projects" add constraint "projects_pkey" PRIMARY KEY using index "projects_pkey";

alter table "public"."projects_events" add constraint "projects_events_pkey" PRIMARY KEY using index "projects_events_pkey";

alter table "public"."projects_events_ressources" add constraint "projects_events_ressources_pkey" PRIMARY KEY using index "projects_events_ressources_pkey";

alter table "public"."projects_exemplarity_indicators" add constraint "projects_exemplarity_indicators_pkey" PRIMARY KEY using index "projects_exemplarity_indicators_pkey";

alter table "public"."projects_materials" add constraint "projects_materials_pkey" PRIMARY KEY using index "projects_materials_pkey";

alter table "public"."projects_materials_uses" add constraint "projects_materials_uses_pkey" PRIMARY KEY using index "projects_materials_uses_pkey";

alter table "public"."projects_publication_status" add constraint "projects_publication_status_pkey" PRIMARY KEY using index "projects_publication_status_pkey";

alter table "public"."projects_ratings" add constraint "projects_ratings_pkey" PRIMARY KEY using index "projects_ratings_pkey";

alter table "public"."projects_users" add constraint "projects_users_pkey" PRIMARY KEY using index "projects_users_pkey";

alter table "public"."users_profiles" add constraint "users_profiles_pkey" PRIMARY KEY using index "users_profiles_pkey";

alter table "public"."users_projects_collections" add constraint "users_projects_collections_pkey" PRIMARY KEY using index "users_projects_collections_pkey";

alter table "public"."users_projects_collections_items" add constraint "users_projects_collections_items_pkey" PRIMARY KEY using index "users_projects_collections_items_pkey";

alter table "public"."users_roles" add constraint "users_roles_pkey" PRIMARY KEY using index "users_roles_pkey";

alter table "public"."project_event_child_type" add constraint "project_event_child_type_child_type_id_fkey" FOREIGN KEY (child_type_id) REFERENCES project_event_type(id) ON DELETE CASCADE not valid;

alter table "public"."project_event_child_type" validate constraint "project_event_child_type_child_type_id_fkey";

alter table "public"."project_event_child_type" add constraint "project_event_child_type_type_id_fkey" FOREIGN KEY (type_id) REFERENCES project_event_type(id) ON DELETE CASCADE not valid;

alter table "public"."project_event_child_type" validate constraint "project_event_child_type_type_id_fkey";

alter table "public"."project_implantation_mode" add constraint "project_implantation_mode_title_key" UNIQUE using index "project_implantation_mode_title_key";

alter table "public"."project_material_origin" add constraint "project_material_origin_label_key" UNIQUE using index "project_material_origin_label_key";

alter table "public"."project_material_origin" add constraint "project_material_origin_title_key" UNIQUE using index "project_material_origin_title_key";

alter table "public"."project_material_type" add constraint "project_material_type_label_key" UNIQUE using index "project_material_type_label_key";

alter table "public"."project_material_type" add constraint "project_material_type_title_key" UNIQUE using index "project_material_type_title_key";

alter table "public"."project_material_use" add constraint "project_material_use_title_key" UNIQUE using index "project_material_use_title_key";

alter table "public"."project_site_usage_parent_category" add constraint "project_site_usage_by_category_usage_id_category_id_key" UNIQUE using index "project_site_usage_by_category_usage_id_category_id_key";

alter table "public"."project_site_usage_parent_category" add constraint "project_site_usage_parent_category_category_id_fkey" FOREIGN KEY (category_id) REFERENCES project_site_usage_category(id) not valid;

alter table "public"."project_site_usage_parent_category" validate constraint "project_site_usage_parent_category_category_id_fkey";

alter table "public"."project_site_usage_parent_category" add constraint "project_site_usage_parent_category_usage_id_category_id_key" UNIQUE using index "project_site_usage_parent_category_usage_id_category_id_key";

alter table "public"."project_site_usage_parent_category" add constraint "project_site_usage_parent_category_usage_id_fkey" FOREIGN KEY (usage_id) REFERENCES project_site_usage(id) not valid;

alter table "public"."project_site_usage_parent_category" validate constraint "project_site_usage_parent_category_usage_id_fkey";

alter table "public"."project_type" add constraint "project_sub_type_title_key" UNIQUE using index "project_sub_type_title_key";

alter table "public"."project_type_parent_category" add constraint "project_sub_type_parent_type_type_id_sub_type_id_key" UNIQUE using index "project_sub_type_parent_type_type_id_sub_type_id_key";

alter table "public"."project_type_parent_category" add constraint "project_type_parent_category_category_id_fkey" FOREIGN KEY (category_id) REFERENCES project_category(id) not valid;

alter table "public"."project_type_parent_category" validate constraint "project_type_parent_category_category_id_fkey";

alter table "public"."project_type_parent_category" add constraint "project_type_parent_category_type_id_fkey" FOREIGN KEY (type_id) REFERENCES project_type(id) not valid;

alter table "public"."project_type_parent_category" validate constraint "project_type_parent_category_type_id_fkey";

alter table "public"."project_type_parent_category" add constraint "project_types_sub_types_type_id_sub_type_id_key" UNIQUE using index "project_types_sub_types_type_id_sub_type_id_key";

alter table "public"."projects" add constraint "projects_category_id_fkey" FOREIGN KEY (category_id) REFERENCES project_category(id) not valid;

alter table "public"."projects" validate constraint "projects_category_id_fkey";

alter table "public"."projects" add constraint "projects_created_by_id_fkey" FOREIGN KEY (created_by_id) REFERENCES users_profiles(user_id) not valid;

alter table "public"."projects" validate constraint "projects_created_by_id_fkey";

alter table "public"."projects" add constraint "projects_implantation_mode_id_fkey" FOREIGN KEY (implantation_mode_id) REFERENCES project_implantation_mode(id) not valid;

alter table "public"."projects" validate constraint "projects_implantation_mode_id_fkey";

alter table "public"."projects" add constraint "projects_site_ownership_id_fkey" FOREIGN KEY (site_ownership_id) REFERENCES project_site_ownership(id) not valid;

alter table "public"."projects" validate constraint "projects_site_ownership_id_fkey";

alter table "public"."projects" add constraint "projects_site_usage_category_id_fkey" FOREIGN KEY (site_usage_category_id) REFERENCES project_site_usage_category(id) not valid;

alter table "public"."projects" validate constraint "projects_site_usage_category_id_fkey";

alter table "public"."projects" add constraint "projects_site_usage_id_fkey" FOREIGN KEY (site_usage_id) REFERENCES project_site_usage(id) not valid;

alter table "public"."projects" validate constraint "projects_site_usage_id_fkey";

alter table "public"."projects" add constraint "projects_title_key" UNIQUE using index "projects_title_key";

alter table "public"."projects" add constraint "projects_type_id_fkey" FOREIGN KEY (type_id) REFERENCES project_type(id) not valid;

alter table "public"."projects" validate constraint "projects_type_id_fkey";

alter table "public"."projects" add constraint "projects_updated_by_id_fkey" FOREIGN KEY (updated_by_id) REFERENCES users_profiles(user_id) not valid;

alter table "public"."projects" validate constraint "projects_updated_by_id_fkey";

alter table "public"."projects_events" add constraint "projects_events_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES projects_events(id) ON DELETE CASCADE not valid;

alter table "public"."projects_events" validate constraint "projects_events_parent_id_fkey";

alter table "public"."projects_events" add constraint "projects_events_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE not valid;

alter table "public"."projects_events" validate constraint "projects_events_project_id_fkey";

alter table "public"."projects_events" add constraint "projects_events_type_id_fkey" FOREIGN KEY (type_id) REFERENCES project_event_type(id) not valid;

alter table "public"."projects_events" validate constraint "projects_events_type_id_fkey";

alter table "public"."projects_events_ressources" add constraint "projects_events_ressources_event_id_fkey" FOREIGN KEY (event_id) REFERENCES projects_events(id) ON DELETE CASCADE not valid;

alter table "public"."projects_events_ressources" validate constraint "projects_events_ressources_event_id_fkey";

alter table "public"."projects_events_ressources" add constraint "projects_events_ressources_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE not valid;

alter table "public"."projects_events_ressources" validate constraint "projects_events_ressources_project_id_fkey";

alter table "public"."projects_exemplarity_indicators" add constraint "projects_exemplarity_indicato_exemplarity_indicator_id_proj_key" UNIQUE using index "projects_exemplarity_indicato_exemplarity_indicator_id_proj_key";

alter table "public"."projects_exemplarity_indicators" add constraint "projects_exemplarity_indicators_exemplarity_indicator_id_fkey" FOREIGN KEY (exemplarity_indicator_id) REFERENCES project_exemplarity_indicator(id) not valid;

alter table "public"."projects_exemplarity_indicators" validate constraint "projects_exemplarity_indicators_exemplarity_indicator_id_fkey";

alter table "public"."projects_exemplarity_indicators" add constraint "projects_exemplarity_indicators_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE not valid;

alter table "public"."projects_exemplarity_indicators" validate constraint "projects_exemplarity_indicators_project_id_fkey";

alter table "public"."projects_materials" add constraint "projects_materials_material_type_id_fkey" FOREIGN KEY (material_type_id) REFERENCES project_material_type(id) not valid;

alter table "public"."projects_materials" validate constraint "projects_materials_material_type_id_fkey";

alter table "public"."projects_materials" add constraint "projects_materials_origin_id_fkey" FOREIGN KEY (origin_id) REFERENCES project_material_origin(id) not valid;

alter table "public"."projects_materials" validate constraint "projects_materials_origin_id_fkey";

alter table "public"."projects_materials" add constraint "projects_materials_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE not valid;

alter table "public"."projects_materials" validate constraint "projects_materials_project_id_fkey";

alter table "public"."projects_materials_uses" add constraint "projects_materials_uses_material_use_id_fkey" FOREIGN KEY (material_use_id) REFERENCES project_material_use(id) not valid;

alter table "public"."projects_materials_uses" validate constraint "projects_materials_uses_material_use_id_fkey";

alter table "public"."projects_materials_uses" add constraint "projects_materials_uses_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE not valid;

alter table "public"."projects_materials_uses" validate constraint "projects_materials_uses_project_id_fkey";

alter table "public"."projects_materials_uses" add constraint "projects_materials_uses_project_material_id_fkey" FOREIGN KEY (project_material_id) REFERENCES projects_materials(id) ON DELETE CASCADE not valid;

alter table "public"."projects_materials_uses" validate constraint "projects_materials_uses_project_material_id_fkey";

alter table "public"."projects_publication_status" add constraint "projects_publication_status_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE not valid;

alter table "public"."projects_publication_status" validate constraint "projects_publication_status_project_id_fkey";

alter table "public"."projects_publication_status" add constraint "projects_publication_status_project_id_key" UNIQUE using index "projects_publication_status_project_id_key";

alter table "public"."projects_publication_status" add constraint "projects_publication_status_updated_by_id_fkey" FOREIGN KEY (updated_by_id) REFERENCES users_profiles(user_id) not valid;

alter table "public"."projects_publication_status" validate constraint "projects_publication_status_updated_by_id_fkey";

alter table "public"."projects_ratings" add constraint "projects_ratings_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE not valid;

alter table "public"."projects_ratings" validate constraint "projects_ratings_project_id_fkey";

alter table "public"."projects_ratings" add constraint "projects_ratings_project_id_user_id_key" UNIQUE using index "projects_ratings_project_id_user_id_key";

alter table "public"."projects_ratings" add constraint "projects_ratings_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users_profiles(user_id) ON DELETE CASCADE not valid;

alter table "public"."projects_ratings" validate constraint "projects_ratings_user_id_fkey";

alter table "public"."projects_ratings" add constraint "projects_ratings_user_id_project_id_key" UNIQUE using index "projects_ratings_user_id_project_id_key";

alter table "public"."projects_users" add constraint "projects_editors_project_id_editor_id_key" UNIQUE using index "projects_editors_project_id_editor_id_key";

alter table "public"."projects_users" add constraint "projects_users_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) not valid;

alter table "public"."projects_users" validate constraint "projects_users_project_id_fkey";

alter table "public"."projects_users" add constraint "projects_users_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users_profiles(user_id) not valid;

alter table "public"."projects_users" validate constraint "projects_users_user_id_fkey";

alter table "public"."projects_users" add constraint "projects_users_user_id_project_id_key" UNIQUE using index "projects_users_user_id_project_id_key";

alter table "public"."users_profiles" add constraint "users_profiles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."users_profiles" validate constraint "users_profiles_user_id_fkey";

alter table "public"."users_profiles" add constraint "users_profiles_user_id_key" UNIQUE using index "users_profiles_user_id_key";

alter table "public"."users_projects_collections" add constraint "users_projects_collections_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users_profiles(user_id) ON DELETE CASCADE not valid;

alter table "public"."users_projects_collections" validate constraint "users_projects_collections_user_id_fkey";

alter table "public"."users_projects_collections_items" add constraint "users_projects_collections_items_collection_id_fkey" FOREIGN KEY (collection_id) REFERENCES users_projects_collections(id) ON DELETE CASCADE not valid;

alter table "public"."users_projects_collections_items" validate constraint "users_projects_collections_items_collection_id_fkey";

alter table "public"."users_projects_collections_items" add constraint "users_projects_collections_items_collection_id_project_id_key" UNIQUE using index "users_projects_collections_items_collection_id_project_id_key";

alter table "public"."users_projects_collections_items" add constraint "users_projects_collections_items_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE not valid;

alter table "public"."users_projects_collections_items" validate constraint "users_projects_collections_items_project_id_fkey";

alter table "public"."users_projects_collections_items" add constraint "users_projects_collections_items_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users_profiles(user_id) ON DELETE CASCADE not valid;

alter table "public"."users_projects_collections_items" validate constraint "users_projects_collections_items_user_id_fkey";

alter table "public"."users_roles" add constraint "users_roles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users_profiles(user_id) ON DELETE CASCADE not valid;

alter table "public"."users_roles" validate constraint "users_roles_user_id_fkey";

alter table "public"."users_roles" add constraint "users_roles_user_id_key" UNIQUE using index "users_roles_user_id_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_project()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$ begin
insert into public.projects_publication_status (project_id)
values (new.id);

return new;

end;

$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$ begin
insert into public.users_profiles (user_id)
values (new.id);

insert into public.users_roles (user_id)
values (new.id);

return new;

end;

$function$
;

CREATE OR REPLACE FUNCTION public.user_has_role(VARIADIC roles user_role[])
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$ begin if auth.role() != 'authenticated' then return false;

else return exists (
	select 1
	from public.users_roles
	where auth.uid() = id
		and role in (roles)
);

end if;

end;

$function$
;

create policy "Anyone can select project type"
on "public"."project_category"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."project_event_child_type"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."project_event_type"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."project_exemplarity_indicator"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."project_material_origin"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."project_material_type"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."project_material_use"
as permissive
for select
to public
using (true);


create policy "Anyone can select project site ownership"
on "public"."project_site_ownership"
as permissive
for select
to public
using (true);


create policy "Anyone can select project site usage"
on "public"."project_site_usage"
as permissive
for select
to public
using (true);


create policy "Anyone can select project site usage category"
on "public"."project_site_usage_category"
as permissive
for select
to public
using (true);


create policy "Anyone can select links between usages and categories"
on "public"."project_site_usage_parent_category"
as permissive
for select
to public
using (true);


create policy "Only admins and project creators can delete a project."
on "public"."projects"
as permissive
for delete
to public
using (((auth.uid() = created_by_id) OR user_has_role(VARIADIC ARRAY['admin'::user_role])));


create policy "Only admins, projects creators and adequately granted users can"
on "public"."projects"
as permissive
for update
to public
using ((user_has_role(VARIADIC ARRAY['admin'::user_role]) OR (auth.uid() = created_by_id) OR (EXISTS ( SELECT 1
   FROM projects_users
  WHERE ((projects_users.project_id = projects.id) AND (projects_users.user_id = auth.uid()) AND (projects_users.granted_role = ANY (ARRAY['admin'::user_role, 'editor'::user_role])))))))
with check ((user_has_role(VARIADIC ARRAY['admin'::user_role]) OR (auth.uid() = created_by_id) OR (EXISTS ( SELECT 1
   FROM projects_users
  WHERE ((projects_users.project_id = projects.id) AND (projects_users.user_id = auth.uid()) AND (projects_users.granted_role = ANY (ARRAY['admin'::user_role, 'editor'::user_role])))))));


create policy "Only authed users can insert projects."
on "public"."projects"
as permissive
for insert
to public
with check (((auth.role() = 'authenticated'::text) AND (auth.uid() = created_by_id)));


create policy "Select published projects, owned projects, or granted projects."
on "public"."projects"
as permissive
for select
to public
using (((EXISTS ( SELECT 1
   FROM projects_publication_status
  WHERE (projects_publication_status.project_id = projects.id))) OR (auth.uid() = created_by_id) OR (EXISTS ( SELECT 1
   FROM projects_users
  WHERE ((projects_users.project_id = projects.id) AND (projects_users.user_id = auth.uid()))))));


create policy "Anyone can select publication status."
on "public"."projects_publication_status"
as permissive
for select
to public
using (true);


create policy "Only admins, creating editors or granted editors can update pub"
on "public"."projects_publication_status"
as permissive
for update
to public
using ((user_has_role(VARIADIC ARRAY['admin'::user_role]) OR (user_has_role(VARIADIC ARRAY['editor'::user_role]) AND ((EXISTS ( SELECT 1
   FROM projects
  WHERE ((projects.id = projects_publication_status.project_id) AND (projects.created_by_id = auth.uid())))) OR (EXISTS ( SELECT 1
   FROM projects_users
  WHERE ((projects_users.project_id = projects_users.project_id) AND (projects_users.user_id = auth.uid()) AND (projects_users.granted_role = ANY (ARRAY['admin'::user_role, 'editor'::user_role])))))))));


create policy "Anyone can see projects ratings for projects they can normally "
on "public"."projects_ratings"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM projects
  WHERE (projects.id = projects_ratings.project_id))));


create policy "Authenticated users can only manage their own ratings for proje"
on "public"."projects_ratings"
as permissive
for all
to public
using (((auth.uid() = user_id) AND (EXISTS ( SELECT 1
   FROM projects
  WHERE (projects.id = projects_ratings.project_id)))))
with check (((auth.uid() = user_id) AND (EXISTS ( SELECT 1
   FROM projects
  WHERE (projects.id = projects_ratings.project_id)))));


create policy "Anyone can select project users."
on "public"."projects_users"
as permissive
for select
to public
using (true);


create policy "Only project creators, admins can insert, update, and delete pr"
on "public"."projects_users"
as permissive
for all
to public
using ((user_has_role(VARIADIC ARRAY['admin'::user_role]) OR (EXISTS ( SELECT 1
   FROM projects
  WHERE ((projects.id = projects_users.project_id) AND (projects.created_by_id = auth.uid()))))));


create policy "Anyone can select user profiles."
on "public"."users_profiles"
as permissive
for select
to public
using (true);


create policy "Users can only update their own profile."
on "public"."users_profiles"
as permissive
for update
to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));


create policy "Anyone can select published collections or collections they own"
on "public"."users_projects_collections"
as permissive
for select
to public
using ((is_published OR (auth.uid() = user_id)));


create policy "Authed users can only manage collections under their uid"
on "public"."users_projects_collections"
as permissive
for all
to public
using (((auth.role() = 'authenticated'::text) AND (auth.uid() = user_id)))
with check (((auth.role() = 'authenticated'::text) AND (auth.uid() = user_id)));


create policy "Anyone can select items for collections and projects they can s"
on "public"."users_projects_collections_items"
as permissive
for select
to public
using (((EXISTS ( SELECT 1
   FROM users_projects_collections
  WHERE (users_projects_collections.id = users_projects_collections_items.collection_id))) AND (EXISTS ( SELECT 1
   FROM projects
  WHERE (projects.id = users_projects_collections_items.project_id)))));


create policy "Authed users can only manage items of existing collections they"
on "public"."users_projects_collections_items"
as permissive
for all
to public
using (((auth.uid() = user_id) AND (EXISTS ( SELECT 1
   FROM users_projects_collections
  WHERE ((users_projects_collections.id = users_projects_collections_items.collection_id) AND (users_projects_collections.user_id = auth.uid()))))))
with check (((auth.uid() = user_id) AND (EXISTS ( SELECT 1
   FROM users_projects_collections
  WHERE ((users_projects_collections.id = users_projects_collections_items.collection_id) AND (users_projects_collections.user_id = auth.uid()))))));


create policy "Anyone can select users roles."
on "public"."users_roles"
as permissive
for select
to public
using (true);


create policy "Only admins can update users roles."
on "public"."users_roles"
as permissive
for update
to public
using (user_has_role(VARIADIC ARRAY['admin'::user_role]))
with check (user_has_role(VARIADIC ARRAY['admin'::user_role]));


CREATE TRIGGER on_new_project AFTER INSERT ON public.projects FOR EACH ROW EXECUTE FUNCTION handle_new_project();

CREATE TRIGGER on_project_update BEFORE UPDATE ON public.projects FOR EACH ROW EXECUTE FUNCTION moddatetime('updated_at');

CREATE TRIGGER on_project_user_update BEFORE UPDATE ON public.projects_users FOR EACH ROW EXECUTE FUNCTION moddatetime('updated_at');

CREATE TRIGGER on_user_update BEFORE UPDATE ON public.users_profiles FOR EACH ROW EXECUTE FUNCTION moddatetime('updated_at');

CREATE TRIGGER on_user_project_collection_update BEFORE UPDATE ON public.users_projects_collections FOR EACH ROW EXECUTE FUNCTION moddatetime('updated_at');

CREATE TRIGGER on_user_project_collection_item_update BEFORE UPDATE ON public.users_projects_collections_items FOR EACH ROW EXECUTE FUNCTION moddatetime('updated_at');

CREATE TRIGGER on_user_role_update BEFORE UPDATE ON public.users_roles FOR EACH ROW EXECUTE FUNCTION moddatetime('updated_at');


