/*
 * ⚠️ WARNING ⚠️
 *
 * This file was generated by the icons vite-plugin. All changes added manually here will be lost on next iteration run of plugin's generators.
 *
 * Generated at: Mon Dec 05 2022 14:58:01 GMT-0500 (GMT-05:00)
 *
 * ⚠️ WARNING ⚠️
 */

export const icons = {
	'alarm': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M20 13 A8 8 0 0 1 12 21 A8 8 0 0 1 4 13 A8 8 0 0 1 20 13 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M6 3L3 6M18 3L21 6', type: 'primary', fill: false, stroke: true },
			{ d: 'M12 9V13L15 16', type: 'primary', fill: false, stroke: true },
		],
	},
	'announcement': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M7.87354 4.81614L3.73468 15.1633C3.28898 16.2775 3.5502 17.5502 4.39879 18.3988L4.60121 18.6012C5.4498 19.4498 6.72245 19.711 7.8367 19.2653L18.1839 15.1265C19.517 14.5932 19.8706 12.8706 18.8553 11.8553L11.1447 4.14471C10.1294 3.12942 8.4068 3.48301 7.87354 4.81614Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M9 19L9.17082 19.3416C9.679 20.358 10.7178 21 11.8541 21H12.1577C14.1094 21 15.5415 19.1658 15.0681 17.2724L15 17',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M16 3C18 4 20 6 21 8', type: 'primary', fill: false, stroke: true },
		],
	},
	'arrow-down-left': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M17 7L7 17M6 8L6 16C6 17.1046 6.89543 18 8 18L16 18',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'arrow-down-right': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M7 7L17 17M18 8L18 16C18 17.1046 17.1046 18 16 18L8 18',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'arrow-down': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M12 5V19M5 13L10.5858 18.5858C11.3668 19.3668 12.6332 19.3668 13.4142 18.5858L19 13',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'arrow-horizontal': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{ d: 'M21 12L3 12', type: 'primary', fill: false, stroke: true },
			{
				d: 'M7 7L3.41421 10.5858C2.63316 11.3668 2.63316 12.6332 3.41421 13.4142L7 17',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M17 17L20.5858 13.4142C21.3668 12.6332 21.3668 11.3668 20.5858 10.5858L17 7',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'arrow-left': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M19 12L5 12M11 5L5.41421 10.5858C4.63316 11.3668 4.63316 12.6332 5.41421 13.4142L11 19',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'arrow-nwse': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M11 3.99998L6 3.99999C4.89543 4 4.00001 4.89542 4.00001 5.99999L4 11',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M13 20L18 20C19.1046 20 20 19.1046 20 18L20 13',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M19 19L5 5', type: 'primary', fill: false, stroke: true },
		],
	},
	'arrow-right': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M5 12L19 12M13 5L18.5858 10.5858C19.3668 11.3668 19.3668 12.6332 18.5858 13.4142L13 19',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'arrow-swne': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M20 11L20 6C20 4.89543 19.1046 4 18 4L13 4',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M4 13L4.00001 18C4.00002 19.1046 4.89544 20 6.00001 20L11 20',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M5 19L19 5', type: 'primary', fill: false, stroke: true },
		],
	},
	'arrow-up-left': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M17 17L7 7M6 16L6 8C6 6.89543 6.89543 6 8 6L16 6',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'arrow-up-right': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M7 17L17 7M8 6L16 6C17.1046 6 18 6.89543 18 8L18 16',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'arrow-up': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M12 19V5M5 11L10.5858 5.41421C11.3668 4.63316 12.6332 4.63317 13.4142 5.41421L19 11',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'arrow-vertical': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{ d: 'M12 21L12 3', type: 'primary', fill: false, stroke: true },
			{
				d: 'M17 7L13.4142 3.41421C12.6332 2.63316 11.3668 2.63316 10.5858 3.41421L7 7',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M7 17L10.5858 20.5858C11.3668 21.3668 12.6332 21.3668 13.4142 20.5858L17 17',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'asterisk': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{ d: 'M12 6L12 18', type: 'primary', fill: false, stroke: true },
			{ d: 'M7 9L17 15M7 15L17 9', type: 'primary', fill: false, stroke: true },
		],
	},
	'bell-ring': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{ d: 'M10 21H14', type: 'primary', fill: false, stroke: true },
			{
				d: 'M13.7487 5.32612C15.7074 6.0279 17.1756 7.79527 17.4172 9.96942L17.7101 12.6055C17.8104 13.5082 18.2149 14.3499 18.8572 14.9922L19.7209 15.8559C20.2466 16.3815 20.0243 17.2361 19.2946 17.3777C17.8352 17.661 15.3587 18 11.865 18C8.3714 18 5.89489 17.661 4.4355 17.3777C3.70574 17.2361 3.48351 16.3815 4.00917 15.8559L4.87288 14.9922C5.51514 14.3499 5.91969 13.5082 6.01999 12.6055L6.31289 9.96942C6.55446 7.79527 8.02265 6.0279 9.98141 5.32612C10.258 4.55309 10.9969 4 11.865 4C12.7332 4 13.4721 4.55309 13.7487 5.32612Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M19 4C20.5 5.5 21 7 21 7', type: 'primary', fill: false, stroke: true },
			{ d: 'M5 4C3.5 5.5 3 7 3 7', type: 'primary', fill: false, stroke: true },
		],
	},
	'bell': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{ d: 'M11 21H13', type: 'primary', fill: false, stroke: true },
			{
				d: 'M13.8837 5.32612C15.8424 6.0279 17.3106 7.79527 17.5522 9.96942L17.8451 12.6055C17.9454 13.5082 18.3499 14.3499 18.9922 14.9922L19.8559 15.8559C20.3815 16.3815 20.1593 17.2361 19.4296 17.3777C17.9702 17.661 15.4937 18 12 18C8.50638 18 6.02987 17.661 4.57048 17.3777C3.84072 17.2361 3.61849 16.3815 4.14414 15.8559L5.00786 14.9922C5.65012 14.3499 6.05467 13.5082 6.15497 12.6055L6.44786 9.96942C6.68944 7.79527 8.15763 6.0279 10.1164 5.32612C10.393 4.55309 11.1319 4 12 4C12.8681 4 13.6071 4.55309 13.8837 5.32612Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'bookmark': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M15 3H9C6.79086 3 5 4.79086 5 7V19.3787C5 20.715 6.61571 21.3843 7.56066 20.4393L11.2929 16.7071C11.6834 16.3166 12.3166 16.3166 12.7071 16.7071L16.4393 20.4393C17.3843 21.3843 19 20.715 19 19.3787V7C19 4.79086 17.2091 3 15 3Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'chevron-down-left': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M16 16L10 16C8.89543 16 8 15.1046 8 14L8 8',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'chevron-down-right': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M16 8V14C16 15.1046 15.1046 16 14 16L8 16',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'chevron-down': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M18 10L13.5185 15.2284C12.7203 16.1596 11.2797 16.1596 10.4815 15.2284L6 10',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'chevron-left': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M14 18L8.7716 13.5185C7.84038 12.7203 7.84038 11.2797 8.7716 10.4815L14 6',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'chevron-right': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M10 6L15.2284 10.4815C16.1596 11.2797 16.1596 12.7203 15.2284 13.5185L10 18',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'chevron-up-left': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M8 16L8 10C8 8.89543 8.89543 8 10 8L16 8',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'chevron-up-right': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M8 8H14C15.1046 8 16 8.89543 16 10L16 16',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'chevron-up': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M6 14L10.4815 8.7716C11.2797 7.84038 12.7203 7.84038 13.5185 8.7716L18 14',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'clock': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M21 12 A9 9 0 0 1 12 21 A9 9 0 0 1 3 12 A9 9 0 0 1 21 12 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M12 7V12L15 15', type: 'primary', fill: false, stroke: true },
		],
	},
	'comment': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M12 19C16.4183 19 20 15.4183 20 11C20 6.58172 16.4183 3 12 3C7.58172 3 4 6.58172 4 11C4 12.6451 4.49658 14.1743 5.34803 15.4457C5.48461 15.6497 5.55524 15.8923 5.53302 16.1368L5.16253 20.2122C5.09159 20.9925 5.90484 21.5476 6.60563 21.1972L10.8356 19.0822C11.0082 18.9959 11.2021 18.963 11.3946 18.9774C11.5944 18.9924 11.7963 19 12 19Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M9 9H10.5H15M9 13H13', type: 'primary', fill: false, stroke: true },
		],
	},
	'cross': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [{ d: 'M6 6L18 18M6 18L18 6', type: 'primary', fill: false, stroke: true }],
	},
	'cursor': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M5.9138 7.21923L10.8425 19.1889C11.2099 20.0813 12.5033 19.9869 12.7373 19.0507L13.4179 16.3283C13.7762 14.8952 14.8952 13.7762 16.3283 13.4179L19.0507 12.7373C19.9869 12.5033 20.0813 11.2099 19.1889 10.8425L7.21923 5.9138C6.39729 5.57536 5.57536 6.39729 5.9138 7.21923Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'dots-horizontal': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M7 12 A1 1 0 0 1 6 13 A1 1 0 0 1 5 12 A1 1 0 0 1 7 12 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M13 12 A1 1 0 0 1 12 13 A1 1 0 0 1 11 12 A1 1 0 0 1 13 12 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M19 12 A1 1 0 0 1 18 13 A1 1 0 0 1 17 12 A1 1 0 0 1 19 12 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'dots-vertical': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M13 6 A1 1 0 0 1 12 7 A1 1 0 0 1 11 6 A1 1 0 0 1 13 6 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M13 12 A1 1 0 0 1 12 13 A1 1 0 0 1 11 12 A1 1 0 0 1 13 12 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M13 18 A1 1 0 0 1 12 19 A1 1 0 0 1 11 18 A1 1 0 0 1 13 18 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'download': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M4 16V16C4 18.2091 5.79086 20 8 20H16C18.2091 20 20 18.2091 20 16V16',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M12 3V13M7 10L10.5858 13.5858C11.3668 14.3668 12.6332 14.3668 13.4142 13.5858L17 10',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'eraser': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M6.17157 19.1716L4.82843 17.8284C3.26633 16.2663 3.26633 13.7337 4.82843 12.1716L12.1716 4.82843C13.7337 3.26633 16.2663 3.26633 17.8284 4.82843L19.1716 6.17157C20.7337 7.73367 20.7337 10.2663 19.1716 11.8284L11.8284 19.1716C10.2663 20.7337 7.73367 20.7337 6.17157 19.1716Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M14.5 21H19', type: 'primary', fill: false, stroke: true },
			{ d: 'M9 14L13 18', type: 'primary', fill: false, stroke: true },
		],
	},
	'exchange-horizontal': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{ d: 'M12 8L21 8', type: 'primary', fill: false, stroke: true },
			{ d: 'M3 16L12 16', type: 'primary', fill: false, stroke: true },
			{
				d: 'M17 13L20.5858 9.41421C21.3668 8.63316 21.3668 7.36683 20.5858 6.58579L17 3',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M7 11L3.41421 14.5858C2.63317 15.3668 2.63316 16.6332 3.41421 17.4142L7 21',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'exchange-vertical': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{ d: 'M8 12L8 3', type: 'primary', fill: false, stroke: true },
			{ d: 'M16 21L16 12', type: 'primary', fill: false, stroke: true },
			{
				d: 'M13 7L9.41421 3.41421C8.63316 2.63316 7.36683 2.63316 6.58579 3.41421L3 7',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M11 17L14.5858 20.5858C15.3668 21.3668 16.6332 21.3668 17.4142 20.5858L21 17',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'exclamation': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{ d: 'M12 14V5', type: 'primary', fill: false, stroke: true },
			{ d: 'M12 19V18.5', type: 'primary', fill: false, stroke: true },
		],
	},
	'expand-arrows': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M4 15V18C4 19.1046 4.89543 20 6 20H9M20 15V18C20 19.1046 19.1046 20 18 20H15M9 4H6C4.89543 4 4 4.89543 4 6V9M15 4H18C19.1046 4 20 4.89543 20 6V9',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M19 5L15 9M5 5L9 9M5 19L9 15M19 19L15 15',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'expand': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M4 15V18C4 19.1046 4.89543 20 6 20H9M20 15V18C20 19.1046 19.1046 20 18 20H15M9 4H6C4.89543 4 4 4.89543 4 6V9M15 4H18C19.1046 4 20 4.89543 20 6V9',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'eye-close': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M21 8C21 10 16.9706 15 12 15C7.02944 15 3 10 3 8',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M5 12L3 14M19 12L21 14M12 15V18M16 14L17 17M7 17L8 14',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'eye-cross': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{ d: 'M4 20L20 4', type: 'primary', fill: false, stroke: true },
			{
				d: 'M20.2544 10C20.734 10.7742 21 11.4861 21 12C21 14 16.9706 19 12 19C11.662 19 11.3283 18.9769 11 18.9332',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M17.1972 6.80284C15.7292 5.75851 13.936 5 12 5C7.02944 5 3 10 3 12C3 13.221 4.50186 15.5602 6.80284 17.1972',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M9.87868 14.1213C8.70711 12.9497 8.70711 11.0502 9.87868 9.87868C11.0503 8.7071 12.9497 8.7071 14.1213 9.87868',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'eye-open': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M21 12C21 14 16.9706 19 12 19C7.02944 19 3 14 3 12C3 10 7.02944 5 12 5C16.9706 5 21 10 21 12Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M15 12 A3 3 0 0 1 12 15 A3 3 0 0 1 9 12 A3 3 0 0 1 15 12 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'file-add': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M14 3V6C14 7.10457 14.8954 8 16 8H19',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M19 11V7.65685C19 6.59599 18.5786 5.57857 17.8284 4.82843L17.1716 4.17157C16.4214 3.42143 15.404 3 14.3431 3H9C6.79086 3 5 4.79086 5 7V17C5 19.2091 6.79086 21 9 21H11',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M9 12H12', type: 'primary', fill: false, stroke: true },
			{ d: 'M18 15V21M15 18H21', type: 'primary', fill: false, stroke: true },
			{ d: 'M9 8H10', type: 'primary', fill: false, stroke: true },
		],
	},
	'file-remove-1': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M14 3V6C14 7.10457 14.8954 8 16 8H19',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M19 11V7.65685C19 6.59599 18.5786 5.57857 17.8284 4.82843L17.1716 4.17157C16.4214 3.42143 15.404 3 14.3431 3H9C6.79086 3 5 4.79086 5 7V17C5 19.2091 6.79086 21 9 21H10',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M9 12H11', type: 'primary', fill: false, stroke: true },
			{ d: 'M9 8H10', type: 'primary', fill: false, stroke: true },
			{ d: 'M15 20L20 15M15 15L20 20', type: 'primary', fill: false, stroke: true },
		],
	},
	'file-remove': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M14 3V6C14 7.10457 14.8954 8 16 8H19',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M19 13V7.65685C19 6.59599 18.5786 5.57857 17.8284 4.82843L17.1716 4.17157C16.4214 3.42143 15.404 3 14.3431 3H9C6.79086 3 5 4.79086 5 7V17C5 19.2091 6.79086 21 9 21H11',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M9 12H12', type: 'primary', fill: false, stroke: true },
			{ d: 'M16 18H21', type: 'primary', fill: false, stroke: true },
			{ d: 'M9 8H10', type: 'primary', fill: false, stroke: true },
		],
	},
	'file': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M5 7C5 4.79086 6.79086 3 9 3H14.3431C15.404 3 16.4214 3.42143 17.1716 4.17157L17.8284 4.82843C18.5786 5.57857 19 6.59599 19 7.65685V17C19 19.2091 17.2091 21 15 21H9C6.79086 21 5 19.2091 5 17V7Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M9 12H15', type: 'primary', fill: false, stroke: true },
			{ d: 'M9 16H13', type: 'primary', fill: false, stroke: true },
			{ d: 'M9 8H10', type: 'primary', fill: false, stroke: true },
			{
				d: 'M14 3V6C14 7.10457 14.8954 8 16 8H19',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'files': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M3 7C3 4.79086 4.79086 3 7 3H11.5375C12.6102 3 13.6378 3.43079 14.3898 4.19564L14.8523 4.66601C15.5878 5.41411 16 6.42124 16 7.47037V16C16 18.2091 14.2091 20 12 20H7C4.79086 20 3 18.2091 3 16V7Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M19 6V6C20.2257 6.61287 21 7.86566 21 9.23607V17.117C21 18.8387 19.8983 20.3672 18.2649 20.9117L18 21',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M11 3V6C11 7.10457 11.8954 8 13 8H16',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M7 12H12', type: 'primary', fill: false, stroke: true },
			{ d: 'M7 16H11', type: 'primary', fill: false, stroke: true },
			{ d: 'M7 8H8', type: 'primary', fill: false, stroke: true },
		],
	},
	'filters': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M4 7.34315V6C4 4.89543 4.89543 4 6 4H18C19.1046 4 20 4.89543 20 6V7.34315C20 8.40401 19.5786 9.42143 18.8284 10.1716L14.8787 14.1213C14.3161 14.6839 14 15.447 14 16.2426V18.5C14 18.8148 13.8518 19.1111 13.6 19.3L12 20.5L11.6 20.8C10.9408 21.2944 10 20.824 10 20V16.2426C10 15.447 9.68393 14.6839 9.12132 14.1213L5.17157 10.1716C4.42143 9.42143 4 8.40401 4 7.34315Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'graph-add': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M20 11V8C20 5.79086 18.2091 4 16 4H8C5.79086 4 4 5.79086 4 8V16C4 18.2091 5.79086 20 8 20H11',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M8 16V11M12 14V8M16 11V10', type: 'primary', fill: false, stroke: true },
			{ d: 'M18 15V21M15 18H21', type: 'primary', fill: false, stroke: true },
		],
	},
	'graph': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M8 4 H16 A4 4 0 0 1 20 8 V16 A4 4 0 0 1 16 20 H8 A4 4 0 0 1 4 16 V8 A4 4 0 0 1 8 4 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M8 16V11M12 16V8M16 16V14', type: 'primary', fill: false, stroke: true },
		],
	},
	'home': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M10.3359 3.1094L4.7812 6.81253C3.6684 7.5544 3 8.80332 3 10.1407V17C3 18.6569 4.34315 20 6 20H8.5C9.32843 20 10 19.3284 10 18.5V15.5C10 14.6716 10.6716 14 11.5 14H12.5C13.3284 14 14 14.6716 14 15.5V18.5C14 19.3284 14.6716 20 15.5 20H18C19.6569 20 21 18.6569 21 17V10.1407C21 8.80332 20.3316 7.5544 19.2188 6.81253L13.6641 3.1094C12.6564 2.4376 11.3436 2.4376 10.3359 3.1094Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'image-add': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M11 20H8C5.79086 20 4 18.2091 4 16V8C4 5.79086 5.79086 4 8 4H16C18.2091 4 20 5.79086 20 8V11',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M11 15L10.2553 14.007C9.45298 12.9373 9.05183 12.4024 8.53991 12.1933C8.14551 12.0322 7.70997 12.0013 7.29675 12.105C6.76041 12.2396 6.28765 12.7124 5.34212 13.6579L4 15',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M16 9.5 A1.5 1.5 0 0 1 14.5 11 A1.5 1.5 0 0 1 13 9.5 A1.5 1.5 0 0 1 16 9.5 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M18 15V21M15 18H21', type: 'primary', fill: false, stroke: true },
		],
	},
	'image-delete': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M10 20H8C5.79086 20 4 18.2091 4 16V8C4 5.79086 5.79086 4 8 4H16C18.2091 4 20 5.79086 20 8V11',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M11 15L10.2553 14.007C9.45298 12.9373 9.05183 12.4024 8.53991 12.1933C8.14551 12.0322 7.70997 12.0013 7.29675 12.105C6.76041 12.2396 6.28765 12.7124 5.34212 13.6579L4 15',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M16 9.5 A1.5 1.5 0 0 1 14.5 11 A1.5 1.5 0 0 1 13 9.5 A1.5 1.5 0 0 1 16 9.5 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M15 20L20 15M15 15L20 20', type: 'primary', fill: false, stroke: true },
		],
	},
	'image-remove': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M11 20H8C5.79086 20 4 18.2091 4 16V8C4 5.79086 5.79086 4 8 4H16C18.2091 4 20 5.79086 20 8V13',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M11 15L10.2553 14.007C9.45298 12.9373 9.05183 12.4024 8.53991 12.1933C8.14551 12.0322 7.70997 12.0013 7.29675 12.105C6.76041 12.2396 6.28765 12.7124 5.34212 13.6579L4 15',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M16 9.5 A1.5 1.5 0 0 1 14.5 11 A1.5 1.5 0 0 1 13 9.5 A1.5 1.5 0 0 1 16 9.5 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M16 18H21', type: 'primary', fill: false, stroke: true },
		],
	},
	'image': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M8 4 H16 A4 4 0 0 1 20 8 V16 A4 4 0 0 1 16 20 H8 A4 4 0 0 1 4 16 V8 A4 4 0 0 1 8 4 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M19 17L17.432 15.432C17.4155 15.4155 17.4072 15.4072 17.4002 15.4003C16.6225 14.6378 15.3775 14.6378 14.5998 15.4003C14.5928 15.4072 14.5845 15.4155 14.568 15.432V15.432C14.5502 15.4498 14.5412 15.4588 14.5338 15.4661C13.7054 16.2774 12.3629 16.2165 11.6114 15.3335C11.6046 15.3256 11.5965 15.3158 11.5804 15.2964L10.2853 13.7424C9.46787 12.7614 9.05914 12.271 8.55647 12.0859C8.16881 11.9432 7.74648 11.9241 7.3475 12.0311C6.83015 12.1699 6.37869 12.6213 5.47576 13.5242L4 15',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M16 9.5 A1.5 1.5 0 0 1 14.5 11 A1.5 1.5 0 0 1 13 9.5 A1.5 1.5 0 0 1 16 9.5 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'info-circle': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M12 17V12C12 11.4477 11.5523 11 11 11H10',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M22 12 A10 10 0 0 1 12 22 A10 10 0 0 1 2 12 A10 10 0 0 1 22 12 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M12 7V7.5', type: 'primary', fill: false, stroke: true },
		],
	},
	'info': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M12 19V11C12 10.4477 11.5523 10 11 10H10',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M10 19H14', type: 'primary', fill: false, stroke: true },
			{ d: 'M12 5V5.5', type: 'primary', fill: false, stroke: true },
		],
	},
	'key': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M20 7.5 A4.5 4.5 0 0 1 15.5 12 A4.5 4.5 0 0 1 11 7.5 A4.5 4.5 0 0 1 20 7.5 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M12 11L4.70711 18.2929C4.07714 18.9229 4.52331 20 5.41421 20H6H6.58579C6.851 20 7.10536 19.8946 7.29289 19.7071L7.5 19.5C7.77614 19.2239 8.22386 19.2239 8.5 19.5V19.5C8.77614 19.7761 9.22386 19.7761 9.5 19.5L10.2929 18.7071C10.6834 18.3166 10.6834 17.6834 10.2929 17.2929L10 17',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'layers': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M4.89443 6.55279L9.76393 4.11803C11.1716 3.41422 12.8284 3.41421 14.2361 4.11803L19.1056 6.55279C19.6537 6.82687 20 7.38713 20 8C20 8.61287 19.6537 9.17313 19.1056 9.44721L14.2361 11.882C12.8284 12.5858 11.1716 12.5858 9.76393 11.882L4.89443 9.44721C4.34626 9.17313 4 8.61287 4 8C4 7.38713 4.34626 6.82687 4.89443 6.55279Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M4 17L9.76393 19.882C11.1716 20.5858 12.8284 20.5858 14.2361 19.882L20 17',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M4 13L9.76393 15.882C11.1716 16.5858 12.8284 16.5858 14.2361 15.882L20 13',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'letter-content': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M21 16V12.2466C21 11.6069 20.4076 11.1316 19.7831 11.2704L12.8677 12.8072C12.2962 12.9342 11.7038 12.9342 11.1323 12.8072L4.21693 11.2704C3.59242 11.1316 3 11.6069 3 12.2466V16C3 18.2091 4.79086 20 7 20H17C19.2091 20 21 18.2091 21 16Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M5 8V6C5 4.34315 6.34315 3 8 3H16C17.6569 3 19 4.34315 19 6V8',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M9 8H15', type: 'primary', fill: false, stroke: true },
		],
	},
	'letter-open': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M3 10.1407C3 8.80332 3.6684 7.5544 4.7812 6.81253L9.7812 3.4792C11.1248 2.58347 12.8752 2.58347 14.2188 3.4792L19.2188 6.81253C20.3316 7.5544 21 8.80332 21 10.1407V16C21 18.2091 19.2091 20 17 20H7C4.79086 20 3 18.2091 3 16V10.1407Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M7 11L11.2155 11.8431C11.7334 11.9467 12.2666 11.9467 12.7845 11.8431L17 11',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'letter': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M7 5 H17 A4 4 0 0 1 21 9 V15 A4 4 0 0 1 17 19 H7 A4 4 0 0 1 3 15 V9 A4 4 0 0 1 7 5 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M7 9L10.1259 11.5007C11.2216 12.3773 12.7784 12.3773 13.8741 11.5007L17 9',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'link': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{ d: 'M10 14L14 10', type: 'primary', fill: false, stroke: true },
			{
				d: 'M8 11.5L7.70643 11.6468C7.23854 11.8807 6.81142 12.1886 6.44152 12.5585L5.5 13.5C4.11929 14.8807 4.11929 17.1193 5.5 18.5V18.5C6.88071 19.8807 9.11929 19.8807 10.5 18.5L11.4415 17.5585C11.8114 17.1886 12.1193 16.7615 12.3532 16.2936L12.5 16',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M16 12.5L16.2936 12.3532C16.7615 12.1193 17.1886 11.8114 17.5585 11.4415L18.5 10.5C19.8807 9.11929 19.8807 6.88071 18.5 5.5V5.5C17.1193 4.11929 14.8807 4.11929 13.5 5.5L12.5585 6.44152C12.1886 6.81142 11.8807 7.23854 11.6468 7.70643L11.5 8',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'localize': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M14 12 A2 2 0 0 1 12 14 A2 2 0 0 1 10 12 A2 2 0 0 1 14 12 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M19 12 A7 7 0 0 1 12 19 A7 7 0 0 1 5 12 A7 7 0 0 1 19 12 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M19 12H21M12 5V3M5 12H3M12 19V21', type: 'primary', fill: false, stroke: true },
		],
	},
	'lock-close-1': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{ d: 'M12 14V16', type: 'primary', fill: false, stroke: true },
			{
				d: 'M18 15 A6 6 0 0 1 12 21 A6 6 0 0 1 6 15 A6 6 0 0 1 18 15 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M16 10V7C16 4.79086 14.2091 3 12 3V3C9.79086 3 8 4.79086 8 7V10',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'lock-close': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{ d: 'M12 15V17', type: 'primary', fill: false, stroke: true },
			{
				d: 'M16 8V7C16 4.79086 14.2091 3 12 3V3C9.79086 3 8 4.79086 8 7V11',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M5 15C5 12.7909 6.79086 11 9 11H15C17.2091 11 19 12.7909 19 15V17C19 19.2091 17.2091 21 15 21H9C6.79086 21 5 19.2091 5 17V15Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'lock-open-1': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{ d: 'M15 15L13 15', type: 'primary', fill: false, stroke: true },
			{
				d: 'M20 15 A6 6 0 0 1 14 21 A6 6 0 0 1 8 15 A6 6 0 0 1 20 15 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M4 10V6C4 4.34315 5.34315 3 7 3V3C8.65685 3 10 4.34315 10 6V10',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'lock-open': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M3 10V6.5C3 4.567 4.567 3 6.5 3V3C8.433 3 10 4.567 10 6.5V11',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M7 15C7 12.7909 8.79086 11 11 11H17C19.2091 11 21 12.7909 21 15V17C21 19.2091 19.2091 21 17 21H11C8.79086 21 7 19.2091 7 17V15Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M15 16L13 16', type: 'primary', fill: false, stroke: true },
		],
	},
	'login': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M6 16V16C6 18.2091 7.79086 20 10 20L15 20C17.2091 20 19 18.2091 19 16L19 8C19 5.79086 17.2091 4 15 4L10 4C7.79086 4 6 5.79086 6 8V8',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M3 12L12 12', type: 'primary', fill: false, stroke: true },
			{
				d: 'M11 9L13.2929 11.2929C13.6834 11.6834 13.6834 12.3166 13.2929 12.7071L11 15',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'logout': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{ d: 'M14 12L3 12', type: 'primary', fill: false, stroke: true },
			{
				d: 'M5 15L2.70711 12.7071C2.31658 12.3166 2.31658 11.6834 2.70711 11.2929L5 9',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M9 16V16C9 18.2091 10.7909 20 13 20L16 20C18.2091 20 20 18.2091 20 16L20 8C20 5.79086 18.2091 4 16 4L13 4C10.7909 4 9 5.79086 9 8V8',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'map': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M3 7.16228C3 5.87099 3.82629 4.72457 5.05132 4.31623L7.60804 3.46399C8.48631 3.17123 9.45054 3.30036 10.2208 3.81388L14.1861 6.45741C14.6996 6.79976 15.3425 6.88585 15.928 6.69068L18.3675 5.87749C19.6626 5.4458 21 6.40974 21 7.77485V16.8377C21 18.129 20.1737 19.2754 18.9487 19.6838L16.392 20.536C15.5137 20.8288 14.5495 20.6996 13.7792 20.1861L9.81388 17.5426C9.30036 17.2002 8.65754 17.1142 8.07203 17.3093L5.63246 18.1225C4.33739 18.5542 3 17.5903 3 16.2251V7.16228Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M9 7V17M15 7V17', type: 'primary', fill: false, stroke: true },
		],
	},
	'minus': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [{ d: 'M6 12H18', type: 'primary', fill: false, stroke: true }],
	},
	'paper-clip': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M11 5L4.5 11.5C2.567 13.433 2.567 16.567 4.5 18.5V18.5C6.433 20.433 9.567 20.433 11.5 18.5L19.5 10.5C20.8807 9.11929 20.8807 6.88071 19.5 5.5V5.5C18.1193 4.11929 15.8807 4.11929 14.5 5.5L7.5 12.5C6.67157 13.3284 6.67157 14.6716 7.5 15.5V15.5C8.32843 16.3284 9.67157 16.3284 10.5 15.5L15 11',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'parameters': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M21 6 A2 2 0 0 1 19 8 A2 2 0 0 1 17 6 A2 2 0 0 1 21 6 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M7 12 A2 2 0 0 1 5 14 A2 2 0 0 1 3 12 A2 2 0 0 1 7 12 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M18 18 A2 2 0 0 1 16 20 A2 2 0 0 1 14 18 A2 2 0 0 1 18 18 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M13 6H3', type: 'primary', fill: false, stroke: true },
			{ d: 'M21 12L11 12', type: 'primary', fill: false, stroke: true },
			{ d: 'M10 18H3', type: 'primary', fill: false, stroke: true },
			{ d: 'M21 18H18', type: 'primary', fill: false, stroke: true },
		],
	},
	'path-circle': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M18 4 H18 A2 2 0 0 1 20 6 V6 A2 2 0 0 1 18 8 H18 A2 2 0 0 1 16 6 V6 A2 2 0 0 1 18 4 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M12 10 H12 A2 2 0 0 1 14 12 V12 A2 2 0 0 1 12 14 H12 A2 2 0 0 1 10 12 V12 A2 2 0 0 1 12 10 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M14 10L16 8', type: 'primary', fill: false, stroke: true },
			{
				d: 'M20.9451 11C20.9814 11.3283 21 11.662 21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C12.338 3 12.6717 3.01863 13 3.05493',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'path-curve': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M6 16 H6 A2 2 0 0 1 8 18 V18 A2 2 0 0 1 6 20 H6 A2 2 0 0 1 4 18 V18 A2 2 0 0 1 6 16 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M18 4 H18 A2 2 0 0 1 20 6 V6 A2 2 0 0 1 18 8 H18 A2 2 0 0 1 16 6 V6 A2 2 0 0 1 18 4 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M6 16C6 13 7.99999 8 12 12C16 16 18 11 18 8',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'path-line': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M6 16 H6 A2 2 0 0 1 8 18 V18 A2 2 0 0 1 6 20 H6 A2 2 0 0 1 4 18 V18 A2 2 0 0 1 6 16 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M18 4 H18 A2 2 0 0 1 20 6 V6 A2 2 0 0 1 18 8 H18 A2 2 0 0 1 16 6 V6 A2 2 0 0 1 18 4 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M7.5 16.5L16.5 7.5', type: 'primary', fill: false, stroke: true },
		],
	},
	'path-multiline': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M16 3 H16 A2 2 0 0 1 18 5 V5 A2 2 0 0 1 16 7 H16 A2 2 0 0 1 14 5 V5 A2 2 0 0 1 16 3 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M23 13 H23 A2 2 0 0 1 25 15 V15 A2 2 0 0 1 23 17 H23 A2 2 0 0 1 21 15 V15 A2 2 0 0 1 23 13 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M9 16 H9 A2 2 0 0 1 11 18 V18 A2 2 0 0 1 9 20 H9 A2 2 0 0 1 7 18 V18 A2 2 0 0 1 9 16 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M6 16L11 7', type: 'primary', fill: false, stroke: true },
			{ d: 'M13 7L17.5 13', type: 'primary', fill: false, stroke: true },
		],
	},
	'pen-plus': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M9.40853 17.5915L18 9C19.1046 7.89543 19.1046 6.10457 18 5C16.8954 3.89543 15.1046 3.89543 14 5L5.40853 13.5915C5.13866 13.8613 4.92276 14.1802 4.77241 14.531L2.9848 18.7021C2.6292 19.5319 3.46814 20.3708 4.29786 20.0152L8.46897 18.2276C8.81977 18.0772 9.13866 17.8613 9.40853 17.5915Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M16 9L17 10', type: 'primary', fill: false, stroke: true },
			{ d: 'M18 15V21M15 18H21', type: 'primary', fill: false, stroke: true },
		],
	},
	'pen': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M10.2724 17.7276L19 9C20.1046 7.89543 20.1046 6.10457 19 5C17.8954 3.89543 16.1046 3.89543 15 5L6.27235 13.7276C6.09244 13.9076 5.9485 14.1202 5.84828 14.354L3.9848 18.7021C3.6292 19.5319 4.46814 20.3708 5.29786 20.0152L9.64598 18.1517C9.87984 18.0515 10.0924 17.9076 10.2724 17.7276Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M17 9L18 10', type: 'primary', fill: false, stroke: true },
		],
	},
	'pin': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M20 11C20 14.4097 16.367 17.8193 13.4365 20.6096C12.6365 21.3713 11.3635 21.3713 10.5635 20.6096C7.63304 17.8193 4 14.4097 4 11C4 6.58172 7.58172 3 12 3C16.4183 3 20 6.58172 20 11Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M15 11 A3 3 0 0 1 12 14 A3 3 0 0 1 9 11 A3 3 0 0 1 15 11 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'plus': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [{ d: 'M12 5L12 19M4.99999 12L19 12', type: 'primary', fill: false, stroke: true }],
	},
	'question-frame': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M22 12 A10 10 0 0 1 12 22 A10 10 0 0 1 2 12 A10 10 0 0 1 22 12 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M12 18V17.5', type: 'primary', fill: false, stroke: true },
			{
				d: 'M12 14.5C11 12 16 13 16 9.5C16 7.29086 14.2091 6 12 6C9.79086 6 8 7.29086 8 9.5',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'question': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M8 9C8 6.79086 9.79086 5 12 5C14.2091 5 16 6.79086 16 9C16 10.5102 14.6957 11.8249 13.1647 12.5057C12.2259 12.9231 11.5406 14.0811 12 15V15',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M12 19V18.5', type: 'primary', fill: false, stroke: true },
		],
	},
	'redo': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M19 14C19 17.866 15.866 21 12 21C8.13401 21 5 17.866 5 14C5 10.134 8.13401 7 12 7H15.5',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M12 11L15.2929 7.70711C15.6834 7.31658 15.6834 6.68342 15.2929 6.29289L12 3',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'save': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M4 8C4 5.79086 5.79086 4 8 4H13.7574C14.553 4 15.3161 4.31607 15.8787 4.87868L19.1213 8.12132C19.6839 8.68393 20 9.44699 20 10.2426V16C20 18.2091 18.2091 20 16 20H8C5.79086 20 4 18.2091 4 16V8Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M8 19V16C8 14.8954 8.89543 14 10 14H14C15.1046 14 16 14.8954 16 16V19',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M11 17H13', type: 'primary', fill: false, stroke: true },
			{
				d: 'M15 5L15 7C15 7.55228 14.5523 8 14 8L10 8C9.44771 8 9 7.55228 9 7L9 5',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'search-clear': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{ d: 'M14 3L19 8M14 8L19 3', type: 'primary', fill: false, stroke: true },
			{ d: 'M17 19L19 21', type: 'primary', fill: false, stroke: true },
			{
				d: 'M9.5 5C5.91015 5 3 7.91015 3 11.5C3 15.0899 5.91015 18 9.5 18C13.0899 18 16 15.0899 16 11.5',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'search': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M16 9.5 A6.5 6.5 0 0 1 9.5 16 A6.5 6.5 0 0 1 3 9.5 A6.5 6.5 0 0 1 16 9.5 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M17 17L19 19', type: 'primary', fill: false, stroke: true },
		],
	},
	'settings': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M8.62688 18.1352C9.40187 18.5622 10 19.3167 10 20.2016C10 20.5381 10.2325 20.8329 10.5648 20.8862C11.0322 20.9611 11.5115 21 12 21C12.4885 21 12.9678 20.9611 13.4352 20.8862C13.7675 20.8329 14 20.5381 14 20.2016C14 19.3167 14.5981 18.5622 15.3731 18.1352C15.4586 18.0881 15.543 18.0392 15.6262 17.9887C16.3825 17.5298 17.3346 17.3893 18.1007 17.8317C18.3925 18.0001 18.7644 17.9463 18.9773 17.6853C19.5801 16.9463 20.0679 16.1099 20.4133 15.2031C20.5337 14.8871 20.3937 14.5367 20.1009 14.3676C19.3354 13.9257 18.9801 13.0318 18.9985 12.1481C18.9995 12.0988 19 12.0495 19 12C19 11.9505 18.9995 11.9012 18.9985 11.8519C18.9801 10.9682 19.3354 10.0743 20.1009 9.63236C20.3937 9.46327 20.5337 9.11288 20.4133 8.79686C20.0679 7.89014 19.5801 7.05366 18.9773 6.31473C18.7644 6.05371 18.3924 5.99992 18.1007 6.16835C17.3346 6.61065 16.3825 6.47018 15.6262 6.01127C15.543 5.96076 15.4586 5.91193 15.3731 5.86483C14.5981 5.43784 14 4.68325 14 3.79841C14 3.46188 13.7675 3.16706 13.4352 3.11381C12.9678 3.03891 12.4885 3 12 3C11.5115 3 11.0322 3.03891 10.5648 3.1138C10.2325 3.16706 10 3.46188 10 3.79841C10 4.68325 9.40187 5.43784 8.62688 5.86484C8.5414 5.91193 8.45702 5.96076 8.37377 6.01127C7.61751 6.47018 6.66537 6.61065 5.89928 6.16835C5.60755 5.99992 5.23564 6.05371 5.02269 6.31473C4.41988 7.05366 3.93211 7.89014 3.5867 8.79685C3.46631 9.11288 3.60627 9.46328 3.89914 9.63236C4.66462 10.0743 5.01987 10.9682 5.00154 11.8519C5.00051 11.9012 5 11.9505 5 12C5 12.0495 5.00051 12.0988 5.00154 12.1481C5.01987 13.0318 4.66462 13.9257 3.89914 14.3676C3.60627 14.5367 3.46631 14.8871 3.5867 15.2031C3.93211 16.1099 4.41988 16.9463 5.02269 17.6853C5.23564 17.9463 5.60755 18.0001 5.89928 17.8317C6.66537 17.3893 7.6175 17.5298 8.37377 17.9887C8.45702 18.0392 8.5414 18.0881 8.62688 18.1352Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M15 12 A3 3 0 0 1 12 15 A3 3 0 0 1 9 12 A3 3 0 0 1 15 12 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'shrink-arrows': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M4 15H7C8.10457 15 9 15.8954 9 17V20M20 15H17C15.8954 15 15 15.8954 15 17V20M9 4V7C9 8.10457 8.10457 9 7 9H4M15 4V7C15 8.10457 15.8954 9 17 9H20',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M20 4L16 8M4 4L8 8M4 20L8 16M20 20L16 16',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'shrink': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M4 15H7C8.10457 15 9 15.8954 9 17V20M20 15H17C15.8954 15 15 15.8954 15 17V20M9 4V7C9 8.10457 8.10457 9 7 9H4M15 4V7C15 8.10457 15.8954 9 17 9H20',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'timer': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M19 14 A7 7 0 0 1 12 21 A7 7 0 0 1 5 14 A7 7 0 0 1 19 14 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M12 11L12 14L14 16', type: 'primary', fill: false, stroke: true },
			{ d: 'M10 3H14', type: 'primary', fill: false, stroke: true },
		],
	},
	'trash': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M4 11L5.35689 17.7845C5.73083 19.6542 7.37249 21 9.27922 21H14.7208C16.6275 21 18.2692 19.6542 18.6431 17.7845L20 11',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M3 7L21 7', type: 'primary', fill: false, stroke: true },
			{ d: 'M10 17V12', type: 'primary', fill: false, stroke: true },
			{ d: 'M14 17V12', type: 'primary', fill: false, stroke: true },
			{
				d: 'M6 7L7.8 4.6C8.55542 3.59278 9.74097 3 11 3H13C14.259 3 15.4446 3.59278 16.2 4.6L18 7',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'undo': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M5 14C5 17.866 8.13401 21 12 21C15.866 21 19 17.866 19 14C19 10.134 15.866 7 12 7H8.5',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M12 11L8.70711 7.70711C8.31658 7.31658 8.31658 6.68342 8.70711 6.29289L12 3',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'unlink': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{ d: 'M5 8L3 7M8 5L7 3', type: 'primary', fill: false, stroke: true },
			{ d: 'M19 16L21 17M16 19L17 21', type: 'primary', fill: false, stroke: true },
			{
				d: 'M7 12L5.5 13.5C4.11929 14.8807 4.11929 17.1193 5.5 18.5V18.5C6.88071 19.8807 9.11929 19.8807 10.5 18.5L13 16',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M17 12L18.5 10.5C19.8807 9.11929 19.8807 6.88071 18.5 5.5V5.5C17.1193 4.11929 14.8807 4.11929 13.5 5.5L11 8',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'upload': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M4 16V16C4 18.2091 5.79086 20 8 20H16C18.2091 20 20 18.2091 20 16V16',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M12 15L12 5M17 8L13.4142 4.41421C12.6332 3.63316 11.3668 3.63316 10.5858 4.41421L7 8',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'user-add': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M14 7 A4 4 0 0 1 10 11 A4 4 0 0 1 6 7 A4 4 0 0 1 14 7 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M11 15.0145C10.681 15.0048 10.3477 15 10 15C5 15 3 16 3 18C3 20 5 21 10 21C10.3477 21 10.681 20.9952 11 20.9855',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M15 18H21M18 15L18 21', type: 'primary', fill: false, stroke: true },
		],
	},
	'user-delete': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M14 7 A4 4 0 0 1 10 11 A4 4 0 0 1 6 7 A4 4 0 0 1 14 7 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M15 20L20 15M15 15L20 20', type: 'primary', fill: false, stroke: true },
			{
				d: 'M10 21C5 21 3 20 3 18C3 16 5 15 10 15',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'user-remove': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M14 7 A4 4 0 0 1 10 11 A4 4 0 0 1 6 7 A4 4 0 0 1 14 7 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M16 18H21', type: 'primary', fill: false, stroke: true },
			{
				d: 'M12 15.0639C11.3951 15.0213 10.7295 15 10 15C5 15 3 16 3 18C3 20 5 21 10 21C10.7295 21 11.3951 20.9787 12 20.9361',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'user': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M16 7 A4 4 0 0 1 12 11 A4 4 0 0 1 8 7 A4 4 0 0 1 16 7 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M19 18C19 20 17 21 12 21C7 21 5 20 5 18C5 16 7 15 12 15C17 15 19 16 19 18Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'users': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M13 7 A4 4 0 0 1 9 11 A4 4 0 0 1 5 7 A4 4 0 0 1 13 7 z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M16 10C17.6569 10 19 8.65685 19 7C19 5.34315 17.6569 4 16 4',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M15 18C15 20 13.2857 21 9 21C4.71429 21 3 20 3 18C3 16 4.71429 15 9 15C13.2857 15 15 16 15 18Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M19 19C19 19 21 18.5 21 16.5C21 14.8333 19.5 14 17 14',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'view-grid': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M4 16C4 14.8954 4.89543 14 6 14H8C9.10457 14 10 14.8954 10 16V18C10 19.1046 9.10457 20 8 20H6C4.89543 20 4 19.1046 4 18V16Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M14 16C14 14.8954 14.8954 14 16 14H18C19.1046 14 20 14.8954 20 16V18C20 19.1046 19.1046 20 18 20H16C14.8954 20 14 19.1046 14 18V16Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M4 6C4 4.89543 4.89543 4 6 4H8C9.10457 4 10 4.89543 10 6V8C10 9.10457 9.10457 10 8 10H6C4.89543 10 4 9.10457 4 8V6Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M14 6C14 4.89543 14.8954 4 16 4H18C19.1046 4 20 4.89543 20 6V8C20 9.10457 19.1046 10 18 10H16C14.8954 10 14 9.10457 14 8V6Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'view-list': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M4 16C4 14.8954 4.89543 14 6 14H18C19.1046 14 20 14.8954 20 16V18C20 19.1046 19.1046 20 18 20H6C4.89543 20 4 19.1046 4 18V16Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{
				d: 'M4 6C4 4.89543 4.89543 4 6 4H18C19.1046 4 20 4.89543 20 6V8C20 9.10457 19.1046 10 18 10H6C4.89543 10 4 9.10457 4 8V6Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'view-masonry-horizontal': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M20 10L20 4M9 18L9 16C9 14.8954 8.10457 14 7 14L6 14C4.89543 14 4 14.8954 4 16L4 18C4 19.1046 4.89543 20 6 20L7 20C8.10457 20 9 19.1046 9 18ZM16 6L16 8C16 9.10457 15.1046 10 14 10L6 10C4.89543 10 4 9.10457 4 8L4 6C4 4.89543 4.89543 4 6 4L14 4C15.1046 4 16 4.89543 16 6ZM20 16L20 18C20 19.1046 19.1046 20 18 20L15 20C13.8954 20 13 19.1046 13 18L13 16C13 14.8954 13.8954 14 15 14L18 14C19.1046 14 20 14.8954 20 16Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'view-masonry-vertical': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M10 20H4M18 9H16C14.8954 9 14 8.10457 14 7V6C14 4.89543 14.8954 4 16 4H18C19.1046 4 20 4.89543 20 6V7C20 8.10457 19.1046 9 18 9ZM6 16H8C9.10457 16 10 15.1046 10 14V6C10 4.89543 9.10457 4 8 4H6C4.89543 4 4 4.89543 4 6V14C4 15.1046 4.89543 16 6 16ZM16 20H18C19.1046 20 20 19.1046 20 18V15C20 13.8954 19.1046 13 18 13H16C14.8954 13 14 13.8954 14 15V18C14 19.1046 14.8954 20 16 20Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
		],
	},
	'warn': {
		width: '24',
		height: '24',
		viewBox: '0 0 24 24',
		paths: [
			{
				d: 'M3.44516 15.5542L9.37135 4.77936C10.5111 2.70703 13.4889 2.70703 14.6286 4.77936L20.5548 15.5542C21.6545 17.5536 20.208 20 17.9262 20H6.07381C3.792 20 2.34552 17.5536 3.44516 15.5542Z',
				type: 'primary',
				fill: false,
				stroke: true,
			},
			{ d: 'M12 8V12', type: 'primary', fill: false, stroke: true },
			{ d: 'M12 16V15.5', type: 'primary', fill: false, stroke: true },
		],
	},
};
