name: Deploy to Heroku

on:
  push:
    paths:
    - 'frontend/**'
    branches:
    - main

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP_NAME: 'nplex-mtl'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: 'frontend'
    - name: Docker build
      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - name: Publish
      run: |
        heroku container:push web -a $HEROKU_APP_NAME
        heroku container:release web -a $HEROKU_APP_NAME
