name: Deploy to Heroku
# Define the action's triggers.
on:
  push:
    paths:
    - 'frontend/**'
    - '.github/**'
    branches:
    - main
# Set the required infos in env vars.
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP_NAME: nplex-mtl
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
# We are only concerned with the frontend package.
defaults:
  run:
    working-directory: frontend
# Define the action's jobs in detail.
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    # Copy things over.
    - name: Checkout
      uses: actions/checkout@v3
    # Build the docker image.
    - name: Docker build
      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    # Send the result to heroku's registry.
    - name: Publish
      run: |
        heroku config:set EXPOSED_SUPABASE_URL=$SUPABASE_URL -a $HEROKU_APP_NAME
        heroku config:set EXPOSED_SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY -a $HEROKU_APP_NAME
        heroku container:push web -a $HEROKU_APP_NAME
        heroku container:release web -a $HEROKU_APP_NAME
